/**
 * Complete Simulation Lambda (Step Functions task)
 * Updates simulation status to 'complete' with completedAt timestamp.
 * Triggers graph-builder Lambda async (fire and forget).
 * Generates transcript and stores in S3.
 */

import { UpdateCommand } from '@aws-sdk/lib-dynamodb';
import { LambdaClient, InvokeCommand, InvocationType } from '@aws-sdk/client-lambda';
import { S3Client, PutObjectCommand } from '@aws-sdk/client-s3';
import { docClient } from '../../lib/dynamodb';

const SIMULATIONS_TABLE_NAME = process.env.SIMULATIONS_TABLE_NAME || 'simulations';
const GRAPH_BUILDER_FUNCTION_NAME = process.env.GRAPH_BUILDER_FUNCTION_NAME || '';
const TRANSCRIPT_BUCKET_NAME = process.env.TRANSCRIPT_BUCKET_NAME || '';

const lambdaClient = new LambdaClient({});
const s3Client = new S3Client({});

export interface CompleteSimulationInput {
  simulationId: string;
  totalRounds: number;
  personaIds: string[];
}

export interface CompleteSimulationOutput {
  simulationId: string;
  status: 'complete';
  completedAt: string;
}

export async function handler(event: CompleteSimulationInput): Promise<CompleteSimulationOutput> {
  const { simulationId, totalRounds, personaIds } = event;
  const now = new Date().toISOString();

  // Update simulation status to complete
  try {
    await docClient.send(
      new UpdateCommand({
        TableName: SIMULATIONS_TABLE_NAME,
        Key: { simulationId },
        UpdateExpression:
          'SET #status = :status, completedAt = :completedAt, taskToken = :emptyToken',
        ExpressionAttributeNames: {
          '#status': 'status',
        },
        ExpressionAttributeValues: {
          ':status': 'complete',
          ':completedAt': now,
          ':emptyToken': null,
        },
      })
    );
  } catch (err) {
    console.error('Failed to update simulation status:', err);
    throw new Error(`Failed to complete simulation ${simulationId}`);
  }

  // Trigger graph-builder Lambda async (fire and forget)
  if (GRAPH_BUILDER_FUNCTION_NAME) {
    try {
      await lambdaClient.send(
        new InvokeCommand({
          FunctionName: GRAPH_BUILDER_FUNCTION_NAME,
          InvocationType: InvocationType.Event, // Async invocation
          Payload: Buffer.from(
            JSON.stringify({
              simulationId,
              totalRounds,
              personaIds,
            })
          ),
        })
      );
    } catch (err) {
      // Fire and forget - don't fail the simulation completion
      console.error('Failed to trigger graph builder:', err);
    }
  }

  // Generate a basic transcript placeholder and store in S3
  if (TRANSCRIPT_BUCKET_NAME) {
    try {
      const transcript = generateTranscriptPlaceholder(simulationId, totalRounds, personaIds);
      await s3Client.send(
        new PutObjectCommand({
          Bucket: TRANSCRIPT_BUCKET_NAME,
          Key: `transcripts/${simulationId}.md`,
          Body: transcript,
          ContentType: 'text/markdown',
        })
      );
    } catch (err) {
      // Don't fail completion if transcript storage fails
      console.error('Failed to store transcript:', err);
    }
  }

  return {
    simulationId,
    status: 'complete',
    completedAt: now,
  };
}

/**
 * Generate a basic transcript placeholder.
 * The full transcript generator (Task 7) will produce the detailed version.
 */
function generateTranscriptPlaceholder(
  simulationId: string,
  totalRounds: number,
  personaIds: string[]
): string {
  const lines: string[] = [
    `# Simulation Transcript: ${simulationId}`,
    '',
    `**Total Rounds:** ${totalRounds}`,
    `**Dealers:** ${personaIds.join(', ')}`,
    `**Completed:** ${new Date().toISOString()}`,
    '',
    '---',
    '',
    '*Full transcript will be generated by the transcript generator.*',
    '',
  ];

  return lines.join('\n');
}
